
name: Create a branch link to a new issue
on:
  issues:
    types: [ assigned ]

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@main
        env:
          repo-token: ${{ secrets.ACCESS_TOKEN }}
